import { EmploymentType, ExperienceLevel, Job } from '@/app/interfaces/api/job.models';

export const mockJobs: Job[] = [
  {
    id: '1',
    title: 'Senior Frontend Developer',
    company: 'TechCorp',
    logo: '/abstract-tech-logo.png',
    keywords: ['Engineering', 'Frontend'],
    location: 'San Francisco, CA',
    employmentType: EmploymentType.FULL_TIME,
    experienceLevel: ExperienceLevel.SENIOR,
    salaryRange: '$120k - $180k',
    techStack: ['React', 'TypeScript', 'Next.js'],
    description:
      "We're looking for a talented Senior Frontend Developer to join our dynamic team. You'll be working on cutting-edge web applications using modern technologies.",
    isActive: true,
    source: 'seeded',
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    title: 'Product Designer',
    company: 'DesignHub',
    logo: '/generic-logo-design.png',
    keywords: ['Design', 'UX/UI'],
    location: 'Remote',
    employmentType: EmploymentType.FULL_TIME,
    experienceLevel: ExperienceLevel.MID,
    salaryRange: '$90k - $140k',
    techStack: ['Figma', 'Design Systems'],
    description:
      'Join our creative team as a Product Designer and help shape the future of our digital products. We value innovation and user-centered design.',
    isActive: true,
    source: 'seeded',
    createdAt: '2024-01-14',
  },
  {
    id: '3',
    title: 'Backend Engineer',
    company: 'DataFlow',
    logo: '/data-logo.png',
    keywords: ['Engineering', 'Backend'],
    location: 'New York, NY',
    employmentType: EmploymentType.FULL_TIME,
    experienceLevel: ExperienceLevel.SENIOR,
    salaryRange: '$130k - $190k',
    techStack: ['Node.js', 'Python', 'Microservices'],
    description:
      "We're seeking an experienced Backend Engineer to build scalable systems and APIs. You'll work with cutting-edge cloud technologies.",
    isActive: true,
    source: 'seeded',
    createdAt: '2024-01-13',
  },
  {
    id: '4',
    title: 'Marketing Manager',
    company: 'GrowthLabs',
    logo: '/abstract-marketing-logo.png',
    keywords: ['Marketing', 'Strategy'],
    location: 'Austin, TX',
    employmentType: EmploymentType.FULL_TIME,
    experienceLevel: ExperienceLevel.SENIOR,
    salaryRange: '$80k - $120k',
    techStack: ['Digital Marketing', 'Analytics'],
    description:
      "Lead our marketing efforts and drive growth through innovative campaigns. We're looking for a creative strategist with proven results.",
    isActive: true,
    source: 'seeded',
    createdAt: '2024-01-12',
  },
  {
    id: '5',
    title: 'DevOps Engineer',
    company: 'CloudScale',
    logo: '/abstract-cloud-logo.png',
    keywords: ['Engineering', 'DevOps'],
    location: 'Seattle, WA',
    employmentType: EmploymentType.FULL_TIME,
    experienceLevel: ExperienceLevel.MID,
    salaryRange: '$110k - $160k',
    techStack: ['AWS', 'Kubernetes', 'CI/CD'],
    description:
      'Join our infrastructure team to build and maintain reliable, scalable cloud systems. Experience with AWS and Kubernetes required.',
    isActive: true,
    source: 'seeded',
    createdAt: '2024-01-11',
  },
  {
    id: '6',
    title: 'Data Scientist',
    company: 'AI Innovations',
    logo: '/ai-logo.png',
    keywords: ['Data Science', 'Machine Learning'],
    location: 'Boston, MA',
    employmentType: EmploymentType.FULL_TIME,
    experienceLevel: ExperienceLevel.SENIOR,
    salaryRange: '$140k - $200k',
    techStack: ['Python', 'R', 'Machine Learning'],
    description:
      "We're looking for a Data Scientist to extract insights from complex datasets and build machine learning models.",
    isActive: true,
    source: 'seeded',
    createdAt: '2024-01-10',
  },
];

