import { Job } from '@/app/models/job.model';

export const mockJobs: Job[] = [
  {
    id: '1',
    title: 'Senior Frontend Developer',
    company: 'TechCorp',
    logo: '/abstract-tech-logo.png',
    category: 'Engineering',
    location: 'San Francisco, CA',
    type: 'Full-time',
    salary: '$120k - $180k',
    postedDate: '2024-01-15',
    description:
      "We're looking for a talented Senior Frontend Developer to join our dynamic team. You'll be working on cutting-edge web applications using modern technologies.",
    requirements: [
      '5+ years of experience with React',
      'Strong TypeScript skills',
      'Experience with Next.js',
      'Understanding of web performance optimization',
    ],
    responsibilities: [
      'Build and maintain web applications',
      'Collaborate with design and backend teams',
      'Write clean, maintainable code',
      'Mentor junior developers',
    ],
    applyUrl: 'https://example.com/apply/1',
  },
  {
    id: '2',
    title: 'Product Designer',
    company: 'DesignHub',
    logo: '/generic-logo-design.png',
    category: 'Design',
    location: 'Remote',
    type: 'Full-time',
    salary: '$90k - $140k',
    postedDate: '2024-01-14',
    description:
      'Join our creative team as a Product Designer and help shape the future of our digital products. We value innovation and user-centered design.',
    requirements: [
      '3+ years of product design experience',
      'Proficiency in Figma and design systems',
      'Strong portfolio showcasing UX/UI work',
      'Experience with user research',
    ],
    responsibilities: [
      'Design user interfaces and experiences',
      'Create wireframes and prototypes',
      'Conduct user research and testing',
      'Collaborate with product and engineering teams',
    ],
    applyUrl: 'https://example.com/apply/2',
  },
  {
    id: '3',
    title: 'Backend Engineer',
    company: 'DataFlow',
    logo: '/data-logo.png',
    category: 'Engineering',
    location: 'New York, NY',
    type: 'Full-time',
    salary: '$130k - $190k',
    postedDate: '2024-01-13',
    description:
      "We're seeking an experienced Backend Engineer to build scalable systems and APIs. You'll work with cutting-edge cloud technologies.",
    requirements: [
      '4+ years of backend development experience',
      'Strong knowledge of Node.js or Python',
      'Experience with microservices architecture',
      'Database design expertise',
    ],
    responsibilities: [
      'Design and implement RESTful APIs',
      'Optimize database performance',
      'Build scalable backend systems',
      'Ensure code quality and security',
    ],
    applyUrl: 'https://example.com/apply/3',
  },
  {
    id: '4',
    title: 'Marketing Manager',
    company: 'GrowthLabs',
    logo: '/abstract-marketing-logo.png',
    category: 'Marketing',
    location: 'Austin, TX',
    type: 'Full-time',
    salary: '$80k - $120k',
    postedDate: '2024-01-12',
    description:
      "Lead our marketing efforts and drive growth through innovative campaigns. We're looking for a creative strategist with proven results.",
    requirements: [
      '5+ years of marketing experience',
      'Experience with digital marketing',
      'Strong analytical skills',
      'Team leadership experience',
    ],
    responsibilities: [
      'Develop marketing strategies',
      'Manage marketing campaigns',
      'Analyze campaign performance',
      'Lead marketing team',
    ],
    applyUrl: 'https://example.com/apply/4',
  },
  {
    id: '5',
    title: 'DevOps Engineer',
    company: 'CloudScale',
    logo: '/abstract-cloud-logo.png',
    category: 'Engineering',
    location: 'Seattle, WA',
    type: 'Full-time',
    salary: '$110k - $160k',
    postedDate: '2024-01-11',
    description:
      'Join our infrastructure team to build and maintain reliable, scalable cloud systems. Experience with AWS and Kubernetes required.',
    requirements: [
      '3+ years of DevOps experience',
      'Strong AWS knowledge',
      'Experience with Kubernetes',
      'CI/CD pipeline expertise',
    ],
    responsibilities: [
      'Manage cloud infrastructure',
      'Implement CI/CD pipelines',
      'Monitor system performance',
      'Automate deployment processes',
    ],
    applyUrl: 'https://example.com/apply/5',
  },
  {
    id: '6',
    title: 'Data Scientist',
    company: 'AI Innovations',
    logo: '/ai-logo.png',
    category: 'Data Science',
    location: 'Boston, MA',
    type: 'Full-time',
    salary: '$140k - $200k',
    postedDate: '2024-01-10',
    description:
      "We're looking for a Data Scientist to extract insights from complex datasets and build machine learning models.",
    requirements: [
      'PhD or Masters in related field',
      'Strong Python and R skills',
      'Machine learning experience',
      'Statistical analysis expertise',
    ],
    responsibilities: [
      'Analyze large datasets',
      'Build predictive models',
      'Present insights to stakeholders',
      'Collaborate with engineering teams',
    ],
    applyUrl: 'https://example.com/apply/6',
  },
];

